language: generic 
sudo: required
services:
   - docker

before_install:
   - docker build -t brunors7/docker-npm -f Dockerfile.dev .

script:
   - docker run -e CI=true brunors7/docker-npm npm run test
